server:
  port: 8761
  
security:  
  basic:  
    enabled: true  
  user:  
    name: admin  
    password: admin123

eureka:
  instance:
    hostname: 10.0.0.2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/